### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Arielfoever** [kingmo888/Spyder_Simplified_Chinese#6]
使用Windows 10 专业版+VS2017带的anaconda，运行main.py报错：
Traceback (most recent call last):
  File "D:\a\main.py", line 46, in <module>
    shutil.copyfile("spyder.mo",zh_CN + r'{0}spyder.mo'.format(flag))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\site-packages\\\\spyder\\\\locale\\\\zh_CN\\\\LC_MESSAGES\\\\spyder.mo'

参考：
- `D:\a\`是我存放该git的路径

**Comment by kingmo888** [comment]
你这个是因为安装在c了。没有权限。

以管理员权限打开cmd，再次执行。
